### ISSUE TITLE
Lemmy 0.19 currently only has a Next button; broke NextPage/PrevPage for me

### ISSUE THREAD

**Issue by heavyboots** [vmavromatis/Lemmy-keyboard-navigation#42]
I have no clue how to do a Git edit, but basically, this code fixes the issue. A little awkward but since we're looking for a case where the Next button may be either at index 0 or 1, this was all I could come up with off the top of my head.

~ Line 890
```
        case nextPageKey:
        case prevPageKey: {
          const pageButtons = Array.from(document.querySelectorAll(".paginator>button"));

          if (pageButtons && (document.getElementsByClassName('paginator').length > 0)) {
            var myNodeList;
            if (event.code === nextPageKey) {
              myNodeList = document.querySelectorAll(".paginator>.btn.btn-secondary");
              for (let i = 0; i < myNodeList.length; i++) {
                  if(myNodeList[i].textContent === "Next") {
                      myNodeList[i].click()
                }
              }
            } else {
              myNodeList = document.querySelectorAll(".paginator>.btn.btn-secondary");
              for (let i = 0; i < myNodeList.length; i++) {
                  if(myNodeList[i].textContent === "Prev") {
                      myNodeList[i].click()
                }
              }
            }
          }
```

**Comment by nicolairathjen** [comment]
> I have no clue how to do a Git edit

This might sound pedandic, but Git has no concept of "Editing". Instead, in Git you will make a new version, and git will track the changes between one version and the next. 

In order to "Edit" this file you will have to:

1. Create a copy of this repository on your own profile (This is called a fork)
2. Make the changes you want to make
3. Save the changes (In Git this is called committing)
4. Create a Pull Request to this repository

The owner of this repository will then have the chance to review your changes, and accept, reject or ask for additional changes.

**Comment by heavyboots** [comment]
OK, thanks. I'll give it a try if I get a chance. Apparently the deletion of the Back button is a permanent thing, so the solution should probably take that into account. Not to mention still being compatible with older versions that do have a back button…
