### ISSUE TITLE
I accidentally unbound the options key

### ISSUE THREAD

**Issue by Kommynct** [vmavromatis/Lemmy-keyboard-navigation#45]
How can I get into the options now?

**Comment by vmavromatis** [comment]
One way to fix this is to open Dev Tools (usually F12) go to appication->local storage and delete the `lemmy-keyboard-navigation-Options` key as such:
<img width="924" alt="image" src="https://github.com/vmavromatis/Lemmy-keyboard-navigation/assets/8668731/7bc0efd3-9bee-46a9-9307-0ac921849867">

otherwise, just click the icon left of the URL then Cookies and site data and delete, however you will also lose your session and will need to log in again
<img width="381" alt="image" src="https://github.com/vmavromatis/Lemmy-keyboard-navigation/assets/8668731/da01a791-1bba-4317-8d04-9838a50a94d5">

Let me know if this helps!

**Comment by Kommynct** [comment]
That worked but there should probably be a more elegant solution like not allowing it to be unbound when you save, so this should probably be left open.
