### ISSUE TITLE
mlmym features 'endless scrolling' 'auto load more' get disabled by this script

### ISSUE THREAD

**Issue by tordenflesk** [vmavromatis/Lemmy-keyboard-navigation#57]
Intended?

**Comment by InfinibyteF4** [comment]
This is intended; the script doesn't work if they're enabled because it depends on there being a set index of posts that get refreshed every time you switch pages

https://github.com/vmavromatis/Lemmy-keyboard-navigation/blob/3ceae76b134d0a423ed8f2903d3a566733731d5d/lemmy-keyboard-navigation-mlmym.user.js#L25
